CREATE TABLE APP_USER (id VARCHAR2(10) CONSTRAINT APP_USER_ID_PK PRIMARY KEY, password VARCHAR2(12), username VARCHAR2(25), birthday DATE, tel VARCHAR2(20), hint VARCHAR2(50));
CREATE TABLE APP_OPPONENT (name VARCHAR2(30) CONSTRAINT APP_OPPONENT_NAME_PK PRIMARY KEY, obank VARCHAR(15), note VARCHAR(300));
CREATE TABLE APP_ACCOUNT (ano NUMBER CONSTRAINT APP_ACCOUNT_ANO_PK PRIMARY KEY, aid VARCHAR2(15), anumber VARCHAR2(30), abalance NUMBER, abank VARCHAR2(15), aliasname VARCHAR2(20) CONSTRAINT APP_USER_OPPONENT_ALIASNAME_UK UNIQUE, CONSTRAINT APP_OPPONENT_AID_FK FOREIGN KEY (aid) REFERENCES APP_USER(id));
CREATE TABLE APP_LOG (lno NUMBER CONSTRAINT APP_LOG_INO_PK PRIMARY KEY, acaliasname VARCHAR2(20), linput NUMBER, loutput NUMBER, ldate DATE, lopponent VARCHAR2(30), CONSTRAINT APP_LOG_ACALIASNAME_FK FOREIGN KEY (acaliasname) REFERENCES APP_ACCOUNT(aliasname), CONSTRAINT APP_LOG_LOPPONENT_FK FOREIGN KEY (lopponent) REFERENCES APP_OPPONENT(name));

-- DROP TABLE APP_USER PURGE;
-- DROP TABLE APP_OPPONENT PURGE;
-- DROP TABLE APP_ACCOUNT PURGE;
-- DROP TABLE APP_LOG PURGE;

-- SELECT TABLE_NAME FROM TABS WHERE TABLE_NAME LIKE 'APP_%'; // 생성완료
-- SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'APP_%';

--test

SELECT * FROM APP_USER;
DESC APP_USER;
ALTER TABLE APP_USER ADD(status NUMBER(1));

